kind: Secret
apiVersion: v1
metadata:
  name: ssl-secret
type: Opaque
data:
  certificat: #{CERTIFICATSSL}
  certificat.crt: #{CERTIFICATCRT}
  certificat.key: #{CERTIFICATKEY}
  certificat.pem: #{CERTIFICATPEM}