apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: my-nginx
spec:
  volumes:
    - name: my-nginx-default-conf
      configMap:
        name: my-nginx-config
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  remplate:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        volumeMounts:
          - name: my-nginx-default-conf
            mountPath: /etc/nginx/conf.d
          - name: my-nginx-pages
            mountPath: /data/up1