kind: Pod
apiVersion: v1
metadata:
  name: my-nginx
spec:
  volumes:
  - name: my-nginx-default-conf
    configMap:
      name: my-nginx-config
  - name: my-nginx-pages
    configMap:
      name: my-nginx-static-file
  containers:
  - name: my-nginx
    image: nginx
    volumeMounts:
    - name: my-nginx-default-conf
      mountPath: /etc/nginx/conf.d
    - name: my-nginx-pages
      mountPath: /data/up1