apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    run: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: http
  selector:
    app: redis