apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerdoc-deployment
  labels:
    app: swaggerdoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swaggerdoc
  template:
    metadata:
      labels:
        app: swaggerdoc
    spec:
      containers:
      - name: swaggerdoc
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{GITHUB_RUN_ID}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: REDIS_HOSTNAME
          value: "localhost"
        resources:
          limits:
            cpu: "0.3"

      - name: redis
        image: redis:5.0.4
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"