apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerdoc-deployment
  labels:
    app: swaggerdoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swaggerdoc
  template:
    metadata:
      labels:
        app: swaggerdoc
    spec:
      containers:
      - name: swaggerdoc
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:460081122
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: REDIS_HOSTNAME
          value: "redis-service"