apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerdoc-deployment
  labels:
    app: swaggerdoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swaggerdoc
  template:
    metadata:
      labels:
        app: swaggerdoc
    spec:
      volumes:
      - name: ssl-volume
        secret:
          secretName: ssl-secret
      containers:
      - name: swaggerdoc
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{GITHUB_RUN_ID}
        ports:
        - containerPort: 443
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: REDIS_HOSTNAME
          value: "10.244.2.42"
        - name: CERTIFICAT_MOT_DE_PASSE
          value: #{CERTIFICAT_MOT_DE_PASSE}
        - name: CERTIFICAT_LOCATION
          value: "/etc/secret"
        - name: CERTIFICAT
          value: "certificat"
        volumeMounts:
        - name: ssl-volume
          mountPath: /etc/secret