apiVersion: v1
kind: Service
metadata:
  name: swaggerdoc-service
  labels:
    run: swaggerdoc
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: swaggerdoc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerdoc-deployment
  labels:
    app: swaggerdoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swaggerdoc
  template:
    metadata:
      labels:
        app: swaggerdoc
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: swaggerdocsecret
      - name: configmap-volume
        configMap:
          name: swaggerdocconfigmap
      containers:
      - name: swaggerdoc
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{GITHUB_RUN_ID}
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/swaggerdpc/ssl
          name: secret-volume
        - mountPath: /etc/swaggerdoc/conf.d
          name: configmap-volume
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: REDIS_HOSTNAME
          value: "10.244.2.42"
