apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerdoc-deployment
  labels:
    app: swaggerdoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swaggerdoc
  template:
    metadata:
      labels:
        app: swaggerdoc
    spec:
      containers:
      - name: swaggerdoc
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{GITHUB_RUN_ID}
        ports:
        - containerPort: 80