apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerdoc-deployment
  labels:
    app: swaggerdoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swaggerdoc
  template:
    metadata:
      labels:
        app: swaggerdoc
    spec:
      containers:
      - name: swaggerdoc
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{GITHUB_RUN_ID}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: REDIS_HOSTNAME
          value: "redis-service"
        - name: CORS_ENABLE
          value: "true"
        - name: CORS_METHODS_ALLOW
          value: "GET,POST"
        - name: CORS_ORIGINES_ALLOW
          value: "*"
        - name: CORS_HEADERS_ALLOW
          value: "Content-Type"