apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-config
data:
  default.conf: |
    server {
            listen              80 default_server;
            listen              [::]:80 default_server;
            server_name         freddycoder.com www.freddycoder.com;
            root /data/up1;
            location /api/ {
                    proxy_pass https://swaggerdoc-apis-service;
            }
    }