apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-static-file
data:
  index.html: |
    <!doctype html>
    
    <html lang="en">
    <head>
      <meta charset="utf-8">
    
      <title>Freddycoder website</title>
      <meta name="description" content="The website develope by freddycoder">
      <meta name="author" content="freddycoder">
    
    </head>
    
    <body>
        <p>Hello from my page!</p>
        <button onclick="callIncrement()">Like</button><span id="likeCount"></span>
      <script>
          var callIncrement = function callIncrement() {
            fetch("/api/redis/callincrement", { method: 'POST' })
                .then(data=>{return data.json()})
                .then(res=>{document.getElementById("likeCount").textContent = res.result});
          }
      </script>
    </body>
    </html>
