apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-config
data:
  default.conf: |
    server {
            listen 8080;
            root /data/up1;

            location / {
            }
    }

    server {
            location / {
                    proxy_pass http://swaggerdoc-apis-service/;
            }
    }