apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-static-file
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Freddycoder website</title>
      <meta name="description" content="The website develope by freddycoder">
      <meta name="author" content="freddycoder">
      <link href="style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
      <h1>Wecome on freddycoder website!</h1>
      <div id="projects">
        <h2>Projects</h2>
        <div id="projet_erabliere_api">
          <h3>ErabliereApi</h3><i>Centralize et share data about mapple sirop</i>
          <a href="https://erabliereapi.freddycoder.com">See demo</a>
          <a href="https://github.com/freddycoder/ErabliereApi">See on Github</a>
        </div>
        <div id="projet_hlhml">
          <h3>HLHML</h3><i>Write script in plain french</i>
          <a href="https://github.com/freddycoder/HLHML">See on Github</a>
        </div>
      </div>
    </body>
    </html>
  style.css: |
    html {
        background-color: #b6b6b6;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    }

    body {
        width: 600px;
        margin: 0 auto;
        background-color: #e2e2e2;
        padding: 0 20px 20px 20px;
        border: 5px solid rgb(255, 255, 255);
    }

    h1 {
        text-align: center;
    }

    button {
        color: blue;
        border-radius: 2ch;
    }
