name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  REGISTRY_HOSTNAME: freddycontainers.azurecr.io
  IMAGE_NAME: swaggerdoc
  DEPLOYMENT_NAME: swaggerdoc
  PORT: 5000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Login into acr
      - name: Login into ACR
        run: docker login $REGISTRY_HOSTNAME -u ${{ secrets.registryUsername }} -p ${{ secrets.registryPassword }}

      # Build the image
      - name: Docker build
        run: docker build -t $IMAGE_NAME:$GITHUB_RUN_ID .
        
      # Tag the images
      - name: Docker tag
        run: docker tag $IMAGE_NAME:$GITHUB_RUN_ID $REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_RUN_ID

      # Push the image
      - name: Docker push
        run: docker push $REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_RUN_ID

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: 'webapidesign'
          cluster-name: 'kubem'

      # Deploy to kubernetes
      - name: Kubectl apply
        run: |
          kubectl config current-context
          kubectl apply -f kubernetes.yaml
