name: CI

on:
  push:
    branches: [ master ]
    
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  REGISTRY_HOSTNAME: registry.digitalocean.com/freddycoderregistry
  IMAGE_NAME: swaggerdoc
  DEPLOYMENT_NAME: swaggerdoc
  EXTERNAL_IPS: 165.22.228.198
  PORT: 5000

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # install the doctl command line tool
      - name: Install the doctl command line tool
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.KUBERNETES_CLUSTER_TOKEN }}

      # Login to digital ocean container registry
      - name: Login into digital ocean container registry
        run: doctl registry login

      # Build the image
      #- name: Docker build
      #  run: docker build -t $IMAGE_NAME:$GITHUB_RUN_ID .
        
      # Tag the images
      #- name: Docker tag
      #  run: docker tag $IMAGE_NAME:$GITHUB_RUN_ID $REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_RUN_ID

      # Push the image
      #- name: Docker push
      #  run: docker push $REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_RUN_ID

      # Build the image nginx
      #- name: Docker build
      #  run: docker build -f ./Infrastructure/nginx-https-ready.dockerfile -t nginx-https-ready:first .
        
      # Tag the images nginx
      #- name: Docker tag
      #  run: docker tag nginx-https-ready:first $REGISTRY_HOSTNAME/nginx-https-ready:first

      # Push the image nginx
      #- name: Docker push
      #  run: docker push $REGISTRY_HOSTNAME/nginx-https-ready:first

      # Connect to kubernetes cluster
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.3
        with:
          personalAccessToken: ${{ secrets.KUBERNETES_CLUSTER_TOKEN }}
          clusterName: kubem
          version: 1.19.3
          expirationTime: "1200"

      # Replace variable in kubernetes file
      - name: Replace variable in k8s file
        uses: cschleiden/replace-tokens@v1.0
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}'
          files: '["./Infrastructure/swaggerdoc.yaml", "./Infrastructure/nginx.yaml", "./Infrastructure/nginx-service.yaml"]'

      # Deploy to kubernetes
      - name: Kubectl apply
        run: |
          kubectl config current-context
          kubectl apply -f ./Infrastructure/nginx-service.yaml
